---
# Handlers for playwright role

- name: Restart valence-server
  systemd:
    name: valence-server
    state: restarted
  when: valence_server_installed is defined and valence_server_installed

- name: Reinstall valence package
  become: yes
  become_user: valence
  pip:
    name: /opt/valence/repo
    virtualenv: /opt/valence/venv
    state: forcereinstall
    editable: yes
  notify: Restart valence-server
