---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart vkb
  service:
    name: vkb
    state: restarted

- name: restart valence-server
  service:
    name: valence-server
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded
